import type { Metadata } from "next";
import { Poppins } from 'next/font/google'; 
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ['latin'], // Choose the subset you need
  weight: ['400', '700'], // Add specific weights (e.g., Regular, Bold)
  variable: '--font-poppins', // Optional: Add a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.variable}
      >
        <Header/>
        <Navbar/>
        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
